// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: skywire.proto

#include "skywire.pb.h"
#include "skywire.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace skywire {

static const char* Skywire_method_names[] = {
  "/skywire.Skywire/Generate",
};

std::unique_ptr< Skywire::Stub> Skywire::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Skywire::Stub> stub(new Skywire::Stub(channel));
  return stub;
}

Skywire::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Generate_(Skywire_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Skywire::Stub::Generate(::grpc::ClientContext* context, const ::skywire::SkywireRequest& request, ::skywire::SkywireResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Generate_, context, request, response);
}

void Skywire::Stub::experimental_async::Generate(::grpc::ClientContext* context, const ::skywire::SkywireRequest* request, ::skywire::SkywireResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, std::move(f));
}

void Skywire::Stub::experimental_async::Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::skywire::SkywireResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, std::move(f));
}

void Skywire::Stub::experimental_async::Generate(::grpc::ClientContext* context, const ::skywire::SkywireRequest* request, ::skywire::SkywireResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, reactor);
}

void Skywire::Stub::experimental_async::Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::skywire::SkywireResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::skywire::SkywireResponse>* Skywire::Stub::AsyncGenerateRaw(::grpc::ClientContext* context, const ::skywire::SkywireRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::skywire::SkywireResponse>::Create(channel_.get(), cq, rpcmethod_Generate_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::skywire::SkywireResponse>* Skywire::Stub::PrepareAsyncGenerateRaw(::grpc::ClientContext* context, const ::skywire::SkywireRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::skywire::SkywireResponse>::Create(channel_.get(), cq, rpcmethod_Generate_, context, request, false);
}

Skywire::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Skywire_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Skywire::Service, ::skywire::SkywireRequest, ::skywire::SkywireResponse>(
          std::mem_fn(&Skywire::Service::Generate), this)));
}

Skywire::Service::~Service() {
}

::grpc::Status Skywire::Service::Generate(::grpc::ServerContext* context, const ::skywire::SkywireRequest* request, ::skywire::SkywireResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace skywire

